# Generated by Django 3.1.4 on 2021-08-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adduser',
            options={'ordering': ['fname']},
        ),
    ]
