# Generated by Django 3.1.4 on 2021-08-07 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210807_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 16, 58, 15, 762082))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adduser')),
            ],
        ),
    ]
