# Generated by Django 3.1.4 on 2021-08-07 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210807_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 17, 13, 18, 412016)),
        ),
    ]
